### ISSUE TITLE
Install dependencies causes pip to install every version of ccxt

### ISSUE THREAD

**Issue by jhoogstraat** [provinzio/CoinTaxman#111]
When installing the dependencies using `pip install -r requirements.txt` every version of ccxt gets installed.

**Example:**
```
Downloading ccxt-1.64.31-py2.py3-none-any.whl (2.2 MB)
     |████████████████████████████████| 2.2 MB 6.8 MB/s
  Downloading ccxt-1.64.30-py2.py3-none-any.whl (2.2 MB)
     |████████████████████████████████| 2.2 MB ...
  Downloading ccxt-1.64.29-py2.py3-none-any.whl (2.2 MB)
     |████████████████████████████████| 2.2 MB ...
  Downloading ccxt-1.64.28-py2.py3-none-any.whl (2.2 MB)
     |████████████████████████████████| 2.2 MB ...
  Downloading ccxt-1.64.27-py2.py3-none-any.whl (2.2 MB)
     |████████████████████████████████| 2.2 MB ...
  Downloading ccxt-1.64.26-py2.py3-none-any.whl (2.2 MB)
     |████████████████████████████████| 2.2 MB 6.8 MB/s
  Downloading ccxt-1.64.25-py2.py3-none-any.whl (2.2 MB)
     |████████████████████████████████| 2.2 MB ...
  Downloading ccxt-1.64.24-py2.py3-none-any.whl (2.2 MB)
     |████████████████████████████████| 2.2 MB ...
  Downloading ccxt-1.64.23-py2.py3-none-any.whl (2.2 MB)
     |████████████████████████████████| 2.2 MB ...
  Downloading ccxt-1.64.22-py2.py3-none-any.whl (2.2 MB)
     |████████████████████████████████| 2.2 MB 6.8 MB/s
```

**Comment by scientes** [comment]
Which pip Version are you using?
And which Branch are you using (prob the ohlcv Branch)
The only similar ocurrence i found Was this: https://github.com/pypa/pip/issues/9284

**Comment by jhoogstraat** [comment]
Yep, I was just testing different branches. I rebased the ohlcv branch onto main though.

**Comment by jhoogstraat** [comment]
The issue is that ccxt has a minimum version, while its dependencies are locked to a specific version. I think it would be better to just include the direct dependencies, like so:
```
ccxt>=1.76.91
python-dateutil==2.8.2
requests==2.27.1
```

**Comment by scientes** [comment]
yeah i need to look at the python modules some are not needed anymore i think. also i couldn't replicate your bug/feature and including the direct dependencies can lead to more issues, e.g. if ccxt updates their dependency version and we locked them pip will throw an error

**Comment by jhoogstraat** [comment]
True, that's what I meant!
There are only 3 dependencies, that have to go into `requirements.txt` (see list above).

**Comment by provinzio** [comment]
I close this issue, as this regarding an unfinished PR #16
