### ISSUE TITLE
No enough to sell

### ISSUE THREAD

**Issue by scientes** [provinzio/CoinTaxman#12]
error:
`2021-03-02 15:16:00,273 taxman       ERROR    test.csv: Line 5: Not enough IOTA in queue to sell (transaction from 2017-12-05 19:30:49+00:00 on binance)`

Minimal reproducible example:
```csv
UTC_Time,Account,Operation,Coin,Change,Remark
2017-12-05 18:03:40,Spot,Buy,IOTA,2.00000000,""
2017-12-05 18:09:03,Spot,Buy,IOTA,2.00000000,""
2017-12-05 19:13:34,Spot,Sell,IOTA,-2.00000000,""
2017-12-05 19:30:49,Spot,Sell,IOTA,-2.00000000,""
```

changing https://github.com/provinzio/CoinTaxman/blob/main/src/bilance_queue.py#L125

```python
if bop is None:
    return None
```
to
 ```python
if bop is None:
     if len(sold_coins)>0:
        return sold_coins
    else:
        return None
 ```

should fix that
 But i'm Not sure how good the fix is

**Comment by provinzio** [comment]
Hey @scientes,

good eye. I fixed the bug.

While testing I realized, that I am unable to gather a price for IOTA/EUR from 2017. IOTA/BTC exists, but I can not find a pair which matches with EUR (e.g. BTCEUR did not existed then).

Do you have an idea for that? Over which pairs have you traded IOTA at that time?

**Comment by scientes** [comment]
IOTA/ETH starts at 2017/09/15
but i do not know how to get from eth to eur that far back on binance
Does coinbase have an api? because they should have ETH/EUR

**Comment by provinzio** [comment]
Have you bought ETH/EUR on binance at that time?

**Comment by scientes** [comment]
yes

**Comment by provinzio** [comment]
Weird that the historical data is missing, but you were able to trade the pair...

Yeah, we should implement a fallback for this situation. I created a specific issue for this #15 because this issue is basically fixed.

**Comment by scientes** [comment]
@provinzio sry i msread i bought via coinbase
