### ISSUE TITLE
Feature: Add nexo.io csv export to compute taxes for interest earned

### ISSUE THREAD

**Issue by gladomat** [provinzio/CoinTaxman#126]
I would love to have a script that computes the taxable events from interest earned on nexo.io. I would also contribute to the feature, I would just need a bit of a primer on how to do it.

**Comment by provinzio** [comment]
Hey @gladomat,

take a look at the keynotes for developers in the readme regarding adding a new exchange. 

You will need some kind of import in book.py. Either with an nexo.io API (if existing) or some kind of transaction statements.

Furthermore it is necessary to define a way to determine prices for your coins at retrieval. Nexo.io might not offer own historical prices? In that case, we could implement some kind of fallback like coingecko, ... See #15 

Feel free to ask any questions.

**Comment by provinzio** [comment]
Closed due to inactivity. Feel free to reopen.
