### ISSUE TITLE
Binance several types and Coinbase one type not recognized

### ISSUE THREAD

**Issue by tobias-p** [provinzio/CoinTaxman#129]
Hi there,

tried to use your app and ran into the following "unsupported" types. Had no problem to map them, but maybe you want to add them:

"Rewards Distribution" -> happened for the Airdrop GAS of Coin NEO, mapped this to "Airdrop"
"Liquid Swap rewards" -> if you collect the Liquid Swap rewards, mapped this to "CoinLendInterest"
"Liquid Swap add/sell" -> not sure, why this occurs, mapped it like "Liquid Swap add" to "CoinLend"

currently have to wait now for my binance history to be processed... if anything else happens, I will open another issue

**Comment by provinzio** [comment]
Hey @tobias-p, thank you for your contribution :)

**Comment by tobias-p** [comment]
> Hey @tobias-p, thank you for your contribution :)

I am happy to help. Also, maybe I can try to help with everything about german taxation since I work as a tax clerk (Steuerfachassistent)...

**Comment by tobias-p** [comment]
Edited the heading, because in Coinbase you also have the possibility of earning rewards for kind of staking...

So I've added (on my pc)

`"Rewards Income": "Staking",`

after line 221 in book.py

**Comment by provinzio** [comment]
> I am happy to help. Also, maybe I can try to help with everything about german taxation since I work as a tax clerk (Steuerfachassistent)...

That would be really kind of you. Glad to have you on the team.
