### ISSUE TITLE
Unable to correctly determine buy cost

### ISSUE THREAD

**Issue by Quadrubo** [provinzio/CoinTaxman#142]
I'm getting the Error: `Unable to correctly determine buy cost of bought coins because the link to the corresponding previous sell could not be estalished. Buying cost will be set to the buy value of the bought coins instead of the sell value of the previously sold coins of the trade. The calculated buy cost might be wrong. This may lead to a false tax evaluation.`. 

Here is my input csv file. Is there anything im doing wrong? Error occurs at row 7 of the csv file.

```csv
Type,Buy Quantity,Buy Asset,Buy Value in EUR,Sell Quantity,Sell Asset,Sell Value in EUR,Fee Quantity,Fee Asset,Fee Value in EUR,Wallet,Timestamp UTC,Note
Deposit,25,EUR,,,,,0.38,EUR,0.38,bitpanda,01/30/2021 13:06:48,
Trade,877.3710876,DOGE,,24.62,EUR,,,,,bitpanda,01/30/2021 13:09:24,
Trade,23.23,EUR,,877.3710876,DOGE,,,,,bitpanda,01/31/2021 18:21:30,
Trade,728.5002973,DOGE,,23.23,EUR,,,,,bitpanda,01/31/2021 18:40:36,
Trade,18.06,EUR,,728.5002973,DOGE,,,,,bitpanda,02/02/2021 15:39:42,
Trade,0.01490654,ETH,,18.06,EUR,,,,,bitpanda,02/02/2021 15:39:42,
```

![image](https://user-images.githubusercontent.com/71718414/189642688-b8934dd2-c2e3-4fa0-9f42-e9a78d2171bd.png)

**Comment by provinzio** [comment]
Feel free to improve the `resolve_trades` function, so that the link can be established automatically. :)
