### ISSUE TITLE
Question: how to see portfolio value from end of year in FIAT currency

### ISSUE THREAD

**Issue by alexanderadam** [provinzio/CoinTaxman#145]
First of all: thank you so much for CoinTaxman! :raised_hands: 
It's working great!

I just have a tiny question:

Would the whole portfolio value the sum of "Unrealisierter Veräußerungserlös in EUR" at the "Bestände" tab?

Thank you again!

**Comment by provinzio** [comment]
Hey @alexanderadam, thanks for your question. 

I find it difficult to understand your question description. Given your title, I believe that you are looking for your current net worth in home fiat (EUR) on all platforms:  

It's mostly the sum of all "Unrealisierter Veräußerungserlös in EUR" which equals the worth of all fiats/coins from all platforms which are not EUR.  

To calculate your full portfolio value in EUR, you have to add deposits in EUR to the "Unrealisierter Veräußerungserlös in EUR". CoinTaxman does not garante to calculate the correct deposits in EUR as this value is not import for tax calculations

**Comment by alexanderadam** [comment]
Wow, you're fast!

Thank you so much, that's what I wanted to hear.

Have a wonderful winter time :snowman_with_snow:
