### ISSUE TITLE
Missing transaction type for "Binance Convert"

### ISSUE THREAD

**Issue by djdesant** [provinzio/CoinTaxman#153]
File "C:\***\Python\CoinTaxman\src\book.py", line 66, in create_operation
    Op = getattr(tr, operation)
AttributeError: module 'transaction' has no attribute 'Binance Convert'

Excel content:
121553843,"2022-01-05   20:15:36","Spot","Binance   Convert","BTC","-0.00331157",""
121553843,"2022-01-05   20:15:36","Spot","Binance   Convert","ETH","0.04031450",""

**Comment by provinzio** [comment]
Looks like regular buy/sell operation. Can you confirm that?

**Comment by djdesant** [comment]
Yes, but it seems to be a Binance's special one with reduced cinversion fees.
See:
[https://www.binance.com/en/support/faq/how-to-use-binance-convert-e8c7579382ea403aa4a4a6eec469659d](url)

**Comment by provinzio** [comment]
Do I understand correctly, that in the example above, BTC was converted to ETH?
