### ISSUE TITLE
ValueError: Operation.change must be positive. - input Kraken Statement

### ISSUE THREAD

**Issue by 19lex82** [provinzio/CoinTaxman#162]
i get the Error: ValueError: Operation.change must be positive. i used kraken Statements

the column "fee"  contains negative values like: -0.3195

does the statement had only positive values before or did i make a mistake?

**Comment by provinzio** [comment]
I do not use kraken myself. Are all your fees negative? Perhaps we need to fix the readin function in book.py

**Comment by 19lex82** [comment]
![image](https://github.com/provinzio/CoinTaxman/assets/34183149/07169677-4141-44d5-ae33-3da586bdb90e)
yes if the is a fee, it is negativ

**Comment by Griffsano** [comment]
If the fee is negative, it seems like the export was changed by Kraken. Could you verify if your export looks like the actions in #97?

If any other fields changed as well, it may be possible to automatically detect the new export format. If everything stayed the same except for the sign of the fee, we could take the absolute value of the fee (if it is guaranteed that a fee is always deducted from the balance and not added).

**Comment by provinzio** [comment]
@19lex82 the PR should offer you a quick fix for your problem.

@Griffsano Instead of using the absolute value, I am checking the fee sign of the file and raise an error, if there are fees with different signs in the same file. As I am not using kraken, it's difficult for me to decide whether this is good to merge; for me it looks like it's ok. Should be good enough, what do you think?

**Comment by Griffsano** [comment]
@provinzio Yes, checking for a consistent sign within a file is even better, #163 looks good to me.
Let's wait for @19lex82 to confirm if anything else changed in the export format.

**Comment by 19lex82** [comment]
i checked the column-headers by the csv download yesterday from kraken. yes looks like column-headers are the same
![image](https://github.com/provinzio/CoinTaxman/assets/34183149/9cf8acaa-2a76-4f11-9c49-754c87b47b66)

**Comment by 19lex82** [comment]
i checked the column-headers by the csv download yesterday from kraken. yes looks like column-headers are the same
image

thanks
