### ISSUE TITLE
Kraken does not work

### ISSUE THREAD

**Issue by jomach** [provinzio/CoinTaxman#170]
Hi, I just checkout main and Downloaded the current ledgers from kraken and I get the error: 

```
2024-08-01 20:50:33,137 book         WARNING  Unable to detect the exchange of file `/Users/xxx/Downloads/CoinTaxman/account_statements/ledgers.csv`. Skipping file.
2024-08-01 20:50:33,137 book         WARNING  Unable to import any data.
2024-08-01 20:50:33,137 __main__     WARNING  Stopping CoinTaxman.
```

**Comment by Griffsano** [comment]
Hmm, I just downloaded a ledgers file from Kraken at it seems fine. Could you check if your CSV header matches this format?:
`"txid","refid","time","type","subtype","aclass","asset","amount","fee","balance"`

If not, please try to download the CSV again according to the [Wiki ](https://github.com/provinzio/CoinTaxman/wiki/Exchange:-Kraken). The history export page on Kraken Pro seems a bit buggy right now, use the export function of the [normal Kraken page](https://www.kraken.com/u/history/export). Kraken Pro and the normal Kraken page are linked, so they should contain the same data.

**Comment by jomach** [comment]
"txid","refid","time","type","subtype","aclass","asset","wallet","amount","fee","balance"
