### ISSUE TITLE
Incorrect tax results

### ISSUE THREAD

**Issue by LEBT48** [provinzio/CoinTaxman#2]
The following input should generate a tax event - if I am correct:

UTC_Time,Account,Operation,Coin,Change,Remark
2020-04-20 16:45:17,Spot,Fee,ETH,-0.0031030,""
2020-04-20 16:45:17,Spot,Buy,ETH,3.1030000,""
2020-04-20 16:45:17,Spot,Sell,EUR,-3320.92707600,""
2021-01-25 06:00:17,Spot,Sell,ETH,-3.0030000,""
2021-01-25 06:00:17,Spot,Buy,EUR,15320.92707600,""

Bought ~ 3 ETH for 3320 EUR and sold it <1 year for 15.000 EUR.
Therefore I made gains that I have to pay taxes on.

The output looks like this:
Date,Taxation Type,Taxed Gain in EUR,Action,Amount,Asset,Remark
2020-04-20 16:45:17,Sonstige Einkünfte,-0.5162864877875,Fee,0.003103,ETH,

Am I missing something?

**Comment by provinzio** [comment]
You have to adjust the `TAX_YEAR` to 2021 in `config.py`. I added the evaluated tax year to the print output for easier recognition.

**Comment by provinzio** [comment]
But the results seem to be incorrect nevertheless. I will look into it.

**Comment by provinzio** [comment]
@LEBT48 Is this your binance statement or have you manipulated it?
Your invested EUR does not match up with the `ETH prices * bought amount` at that time.

The software is actually ignoring the "real trade". It only looks at your Sell/Buy positions and gatheres the prices independently.

Your example gives me this output, which looks quite ok for the prices of ETH, but not with your paid/got EUR amount
```
Your tax evaluation for 2021:
Sonstige Einkünfte: 3008.2247138212424 EUR
```

**Comment by LEBT48** [comment]
Those were manipulated prices, that's correct. 
Results seems reasonable. Thanks a lot!

Still trying to figure the whole python-thing out ... :)
