### ISSUE TITLE
Proper Python linting (with flake8)

### ISSUE THREAD

**Issue by wearymanateevedaknotstabooresisting** [provinzio/CoinTaxman#25]
Currently, the code base is not well linted with respect to Python PEP-8. 

I propse a linting of the code base by using `flake8` to remove unused code, more explicit importing and adjust to consistent line lengths. This has been decided with to `max-line-length=88` in the comments below.

I saw, that a lot of star-imports where used and that pylint was configured to ignore them (see `main.py`). The pythonic way would be to import modules and reference accordingly, like `bilance_queue.BilanceQueue`. If this is unwanted, we could move to a bit less favoured way to explicitly import the needed classes and functions from the model. However, star imports can confuse with increasing code-base complexity.

**Comment by provinzio** [comment]
Hey @wearymanateevedaknotstabooresisting, you are right. I have programmed sloppily, because I was too lazy to type `transaction.xxx` each time. Lets fix this.

I'd prefer to avoid explicit imports where we can. I think that using `bilance_queue.BilanceQueue` helps alot to understand and comprehend the code.

If we want to enforce a specific line length, I'd prefer to stick with a narrow line length, allowing a comfortable use of a splitted editor. Talking numbers, I would go with something in the range of 79-100.

We should add a github workflow, which checks for correct linting.

While cleaning up the code, we could think of something like `autopep8`, too.

**Comment by wearymanateevedaknotstabooresisting** [comment]
I'd stick with the default `max-line-length=79` in that case. However, this may create some issue with more nested files, like longer expressions in class methods, where we already lose a lot characters due to indentation (class, method, for/while, if/else, longer variable name).

While `flake8` hints towards linting issues, `autopep8` is there to automatically fix them. I found some GitHub actions for the CI workflow (see https://github.com/marketplace/actions/flake8-action), but I am really not familiar with CI in GitHub - just program them all myself for GitLab-CI.

**Comment by provinzio** [comment]
> I'd stick with the default `max-line-length=79` in that case. However, this may create some issue with more nested files, like longer expressions in class methods, where we already lose a lot characters due to indentation (class, method, for/while, if/else, longer variable name).

Thats true... We could have a look at our code, and check if we can realize 79 as a line length. 88 would be fine for me too. If that's still a problem, we could raise it to 99.

> but I am really not familiar with CI in GitHub - just program them all myself for GitLab-CI.

Yeah, me too, but your link looks promissing. I'd hope, that his library detects flake8's config file per default. Otherwhise we should look into it. I'd like to add our flake8 config to the repo.

**Comment by provinzio** [comment]
@wearymanateevedaknotstabooresisting what do you think about adding `mypy` to our linting strategy? We could extend the scope of this issue/PR and fix the left over errors on the go

I played a bit with `mypy` on the `mypy` branch, which could be rebased onto the PR branch.
If we want to use `mypy` we should consider, moving all configs to `setup.cfg`.
```
src\transaction.py:44: error: "Operation" has no attribute "__dataclass_fields__"  [attr-defined]
src\balance_queue.py:149: error: Returning Any from function declared to return "BalancedOperation"  [no-any-return]
src\price_data.py:201: error: Returning Any from function declared to return "float"  [no-any-return]
src\price_data.py:204: error: Returning Any from function declared to return "float"  [no-any-return]
src\price_data.py:234: error: Returning Any from function declared to return "Optional[float]"  [no-any-return]
src\price_data.py:294: error: Function is missing a type annotation for one or more arguments  [no-untyped-def]
src\taxman.py:151: error: Returning Any from function declared to return "SupportsLessThan"  [no-any-return]
```

**Comment by wearymanateevedaknotstabooresisting** [comment]
I like this suggestion, since you already coded a lot with static typing. I have no experience with `mypy`, yet. Therefore, I can't contribute more valuable feedack.

Can you elaborate, which are "all configs" and why it's the `setup.cfg` which does not exist yet?

**Comment by provinzio** [comment]
It seems like many "helping" modules like mypy and flake8 support setup.cfg per default. I created one in the mypy branch. When we rebase it onto the PR branch, we could merge the .flake8 content to setup.cfg.

**Comment by wearymanateevedaknotstabooresisting** [comment]
@provinzio rebased PR branch to mypy branch and force pushed to PR.
