### ISSUE TITLE
Rename "bilance" to "balance"

### ISSUE THREAD

**Issue by shredEngineer** [provinzio/CoinTaxman#26]
As the title says, we should rename all occurences of "bilance" to "balance". ([https://www.dict.cc/?s=bilanz](https://www.dict.cc/?s=bilanz))
(Not critical, but preferable. :))

**Comment by provinzio** [comment]
Go ahead and make a PR. Should be a quick fix with Find&Replace. :)

**Comment by shredEngineer** [comment]
Yep, will do that in the future. Right now, I think this would cause a "merge nightmare" for the other PRs. :D

**Comment by provinzio** [comment]
I think, we should not wait for this and fix it as quickly as possible. @wearymanateevedaknotstabooresisting you should look out for 8a07f42654b2535458cf98b4925cc89cb33fe09d which might force you to merge some conflicts.
