### ISSUE TITLE
Floating point issues lead to missing transactions exception

### ISSUE THREAD

**Issue by sibbl** [provinzio/CoinTaxman#28]
I'm currently setting this project up. However, I quickly ran into floating point issues which show up as `Is your account statement missing any transactions? This error may also occur after deposits from unknown sources.` exceptions.

I have the following `BUY` statements: `4.494 + 45.5 + 0.006 = 50` and the `SELL` statements `8.37 + 16.57 + 0.67 + 3.59 + 0.01 + 0.01 + 16.05 + 4.73 = 50`. Both lists here are in the order they're actually being evaluated.

Now what happens when `balance_queue.sell` is called with the final change of `4.73`?
1. There's one last `BalancedOperation` in the queue with the value `45.5`
1. In the `while` loop, `not_sold` is calculated like the following (those are real life debug statements):
```
not_sold = 45.5 - 40.77
not_sold = 4.729999999999997
--> the else case is taken and change is set to 3.552713678800501e-15
```
3. The while loop then sees that `change > 0` is still true and tries to get the next item from the queue... which fails.

Unfortunately I'm not very familiar with Python but coming from other programming languages, I wonder whether `decimal` is a suitable approach here or whether there are better solutions like using some `money` packages.

**Comment by provinzio** [comment]
Hey @sibbl, thank you for your contribution.

I am unsure how we should tackle the floating-point error best. Replacing all `float` with `decimal.Decimal` might be the easiest way. As long as we keep in mind, that we use `decimal.Decimal('1.4')` instead of `decimal.Decimal(1.4)`.

We should resolve this as soon as #25 is done to avoid unnecessary git conflicts. Also the added/fixed linting might help us here.

**Comment by sibbl** [comment]
@provinzio thanks for your quick reply!

After a quic k and dirty replacement of `float` with `Decimal` I can confirm that my problem went away. Looking forward to #25 being resolved so that this issue can be tackled.

**Comment by provinzio** [comment]
@sibbl Would you be so nice and run a test with your account statements. The commit should resolve this issue fully.

**Comment by sibbl** [comment]
@provinzio can confirm that it's working perfectly now 👌 thanks a lot!
