### ISSUE TITLE
New exchange: Coinbase Pro 

### ISSUE THREAD

**Issue by sibbl** [provinzio/CoinTaxman#29]
I'd love to see Coinbase Pro as part of this tool and already started implementing it 🚀

For getting the prices, the [official API for "Getting historical rates"](https://docs.pro.coinbase.com/#get-historic-rates) can be used. My plan would be to get the nearest historic rate with the smallest granularity and use the average of `high` and `low` values.

However, there's the problem that Coinbase doesn't support XRP anymore and has removed the historical data from their API. I'm not sure how to tackle this. Should the tool be extended to use other exchances as kind of a fallback strategy?

**Comment by provinzio** [comment]
We also thought about a fallback in #15. We can't get around it. In tax calculation it's no option to miss a price for a transaction.

You might want to have a look at #16. We started to implement `ccxt` which supports numerous exchanges. The first approach covers only binance though, but we planned to spread it to other exchanges which could include Coinbase Pro (it seems to be supported by `ccxt`, too).

It might be possible, that you assist @scientes on his PR.
