### ISSUE TITLE
Add more binance csv operations

### ISSUE THREAD

**Issue by scientes** [provinzio/CoinTaxman#34]
binance has some products which are not yet implemented fully:
https://www.binance.com/de/earn#flex-item

For Example binance has a product called bnb vault and launchpool which generate some interesting statement currently not implemented:
https://launchpad.binance.com/
here is  one from tests (bnb vault):
```
2021-03-18 01:02:29,Spot,Super BNB Mining,ALICE,0.00006904,""
```

should we count that as normal staking?

ill test it some more to generate statement we currently do not know

**Comment by scientes** [comment]
this should be interersting for #19

**Comment by provinzio** [comment]
Mining is currently not considered in the README. We should add a small text there.

I am unsure whether Mining is taxed like CoinLendInterest. Intuitivly I would add it to Staking... but real Mining might actually  be commercial in Germany.. which might be taxed completly different.

**Comment by scientes** [comment]
This is actually not mining but Coin lending since this is coming from a launchpool distribution

**Comment by provinzio** [comment]
Well, currently we differentiate between `StakingInterest` and `CoinLending` although programatically both are the same atm. But I'd like to keep them seperated in case we want to apply different taxation rules on them.

So what should we do with this weird operation.... Intuitivly I'd would see it as staking (which might be more taxed).

**Comment by scientes** [comment]
i looked a little bit more into it. This should be all lines associated with this product:
```csv
2021-03-17 14:38:38,Spot,Savings purchase,BNB,-0.05000000,""
2021-03-18 01:02:29,Spot,Super BNB Mining,ALICE,0.00006904,""
2021-03-19 04:06:17,Spot,Savings Interest,BNB,9.1E-7,""
2021-03-19 09:52:28,Spot,Super BNB Mining,ALICE,0.00019208,""
2021-03-20 00:52:25,Spot,Super BNB Mining,ALICE,0.00017377,""
2021-03-20 03:48:17,Spot,Savings Interest,BNB,9.1E-7,""
2021-03-21 00:10:03,Spot,Savings Principal redemption,LDBNB,-0.05000000,""
2021-03-21 00:10:03,Spot,Savings Principal redemption,BNB,0.05000000,""
2021-03-21 01:02:25,Spot,Super BNB Mining,ALICE,0.00017357,""
2021-03-21 03:47:09,Spot,Savings Interest,BNB,9.1E-7,""
```
it looks like it split it in seperate positions and  i think that The `SUPER BNB MINING` is the associated asset that come from the launchpool (due to it being another coin, and launchpool is the only project wich does payout in non bnb coins ) and launchpool interests we view as staking. Also does the weird LDBNB affect us? i do not know why that is there

**Comment by provinzio** [comment]
Yeah. I would count Launchpool intuitively to Staking (without research). 

The coins are separated for tax calculation. So FIFO would be fucked up if LDBNB is meant to be BNB. CoinTaxman is currently treating them as different.
I think it's ok they are treated as different coins.

**Comment by scientes** [comment]
Ldbnb: https://twitter.com/moorx/status/1362390178556481538?s=19

So i think this just Shows that the savings Account loses the 0.05 it put at the Start. Due to that we are only interested in Spot i think we can safely ignore that

**Comment by provinzio** [comment]
I don't see the full thread without twitter account. So I don't know what
you are talking about.

**Comment by scientes** [comment]
It's just the two tweets nothinh more but the gist of it is that all binance earn/savings assets are prefixed with an LD

**Comment by provinzio** [comment]
Ah ok, so the when you put something into savings, the statement says

```
Putting 5 EUR in savings
Receving 5 LDEUR in savings
```

And when you close your savings account it says

```
Removing 5 LDEUR from savings
Receiving 5 LDEUR from savings
```

Do I understand it correctly?

I am only having normal BTC savings.. which gives me these two operations.
```
"Savings purchase": "CoinLend",
"Savings Principal redemption": "CoinLendEnd",
```

Although the LDEUR movements should be ignored (and in this case are ignored) for the calculation of the tax, it might be necessary to track the changes, when there are tax regulations which change the taxation depending on the fact that you lended your coins.

**Comment by scientes** [comment]
well the problem with that is that in my csv files i couldnt find another LD statement except the redemption

**Comment by provinzio** [comment]
ok, thats weird... mine match. do you have the full history?

**Comment by scientes** [comment]
i should have, the test period is right in the middle of my export from binance

**Comment by provinzio** [comment]
Ok, we should keep this in mind and check it in a different issue. Let's focus on the current PR.

I'd propose that we add it as Stacking.
