### ISSUE TITLE
Parsing fails when change is equal to "0E-X"

### ISSUE THREAD

**Issue by jhoogstraat** [provinzio/CoinTaxman#39]
When change is in scientific notation, for example "0E-8", the assertion fails (book.py, line 112).
This does only occur when binance produces these strange 0E-X outputs.

**Comment by provinzio** [comment]
The assert fails when change == 0. I thought it would never happen that the value is 0. Therefore the assert. 

Would you share your statement as an example?

**Comment by jhoogstraat** [comment]
I have four lines in my statement that look like this:
2021-04-06 09:49:37,Spot,Transaction Related,EUR,0E-8,""
All are are 0E-8 specifically.

I don't know if its related to this issue, but removing these four lines, parsing succeedes, but evaluation fails (balance_queue.py, line 95, assert not_sold > 0).
Is there a documentation about the binance output? Not too easy to investigate the issue without deeper knowledge.

**Comment by provinzio** [comment]
Do you have the full history? The not sold Error will occur if you sell more coins in your statement than you bought. 

It might be also related to a coin deposit from another exchange for which you have not added your statement. 

----

I have unfortunately no idea what these 0 EUR (Transaction related) might mean. But it shouldn't make a change regarding the tax calculation. (I mean it's 0 after all).

**Comment by jhoogstraat** [comment]
Yeah I did move coins from Coinbase to Binance at one point..
What should I do in this event?

**Comment by provinzio** [comment]
To evaluate your taxes, the program needs to know all of your buys/sells. Fortunatly coinbase is also (kind of) supported by CoinTaxman. In the best case you'll have your coinbase statement and include it, too.

**Comment by jhoogstraat** [comment]
Ah no, I only used Binance's statement. It is still complicated as I used Coinbase and Coinbase Pro...

**Comment by provinzio** [comment]
There is a PR implementing Coinbase Pro support (#31). It might be already functional, you might want to check that out.

**Comment by jhoogstraat** [comment]
Ah nice!
Sadly it does not work as indended. How can the taxman know that I transfered the coins from coinbase to binance?

**Comment by provinzio** [comment]
It doesn't. And it doesn't matter from where the coins come. It's just amount when you bought and sold. 

And currently the history are given is missing some buys.

**Comment by jhoogstraat** [comment]
Well, I don't know how that could have happened. Gonna generate a new statement from binance..

**Comment by provinzio** [comment]
Well, if your history is only partially it's possible that you are missing some buys. E.g. you bought 1 btc on coinbase. Transfered 1 btc to binance and sold 1 btc in binance. If you only add the binance statement CoinTaxman will raise an error, because it's missing the information about the buy operation.

**Comment by jhoogstraat** [comment]
Yeah the statements have to be coherent. I am pretty sure, the statement is complete and does not miss any buys or sells.
I did some investigation and the corresponding operation looks like this:
bop.op.change = 0.01028688
bop.sold = 0.01028688
not_sold = 0E-8

Is 0E-8 expected? Kinda seems like the two issues are connected, no?

**Comment by provinzio** [comment]
Would you mind to test your account statment with ne newest commit again? I might have fixed your problem.

**Comment by jhoogstraat** [comment]
As you did not touch book.py in your newest commit, I guess assert change should still trigger (and it does).
Removing these "0E-8" entries, the code runs fine.

**Comment by provinzio** [comment]
Ah yeah, nvm. I thought of something different. 

From when are the prices? If they are not older than 3 years would you mind sharing the coin type and the date?

**Comment by jhoogstraat** [comment]
Here are some examples:

https://api.binance.com/api/v3/aggTrades?symbol=ROSEBTC&startTime=1617870231000&endTime=1617870291000
https://api.binance.com/api/v3/aggTrades?symbol=MDTBTC&startTime=1617955766000&endTime=1617955826000
https://api.binance.com/api/v3/aggTrades?symbol=BTSBTC&startTime=1616737067000&endTime=1616737127000
https://api.binance.com/api/v3/aggTrades?symbol=ARPABTC&startTime=1617750754000&endTime=1617750814000
https://api.binance.com/api/v3/aggTrades?symbol=DENTBTC&startTime=1618057819000&endTime=1618057879000
https://api.binance.com/api/v3/aggTrades?symbol=QTUMBTC&startTime=1618154304000&endTime=1618154364000
https://api.binance.com/api/v3/aggTrades?symbol=LUNAEUR&startTime=1618938629000&endTime=1618938689000
https://api.binance.com/api/v3/aggTrades?symbol=UNIEUR&startTime=1618923446000&endTime=1618923506000

**Comment by provinzio** [comment]
Is this still an issue? Could have been solved by changing the saved prices from float to string.

**Comment by jhoogstraat** [comment]
I am positive that the issue was fixed, but I'll test using my statements later.
