### ISSUE TITLE
New exchange: Bitpanda Pro

### ISSUE THREAD

**Issue by uvok** [provinzio/CoinTaxman#42]
I was in the process of writing a Python script for myself when I was pointed here.

I'd like to import data from the "Bitpanda Pro" exchange. I'd be willing to submit a PR, once I get familiar with the codebase.

The API documentation is provided here: https://developers.bitpanda.com/exchange/.
The API endpoint for trades is https://developers.bitpanda.com/exchange/#all-trades

The returned data contains the fee *separately*, that is, the trade is given without the fee. The API uses pagination. If the 'cursor' entry is in the JSON data, there's more data.

Sample data for trades:

```
{'cursor': 'base64data',
 'max_page_size': 5,
 'trade_history': [{'fee': {'collection_type': 'BEST',
                            'fee_amount': 'XXX',
                            'fee_currency': 'BEST',
                            'fee_group_id': 'default',
                            'fee_percentage': '0.08',
                            'fee_type': 'MAKER',
                            'running_trading_volume': 'XXX'},
                    'trade': {'account_id': 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx',
                              'amount': 'XXX',
                              'instrument_code': 'PAN_EUR',
                              'order_id': 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx',
                              'price': 'XXX',
                              'price_tick_sequence': 0,
                              'sequence': 1663784546,
                              'side': 'SELL',
                              'time': '2021-04-22T00:00:00.000000Z',
                              'trade_id': 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx'}},
                   {'fee': {'collection_type': 'BEST',
                            'fee_amount': 'XXX',
                            'fee_currency': 'BEST',
                            'fee_group_id': 'default',
                            'fee_percentage': '0.08',
                            'fee_type': 'MAKER',
                            'running_trading_volume': 'XXX'},
                    'trade': {'account_id': 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx',
                              'amount': 'XXX',
                              'instrument_code': 'PAN_EUR',
                              'order_id': 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx',
                              'price': 'XXX',
                              'price_tick_sequence': 0,
                              'sequence': 1663783772,
                              'side': 'SELL',
                              'time': '2021-04-22T00:00:00.000000Z',
                              'trade_id': 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx'}},
                   {'fee': {'collection_type': 'BEST',
                            'fee_amount': 'XXX',
                            'fee_currency': 'BEST',
                            'fee_group_id': 'default',
                            'fee_percentage': '0.12',
                            'fee_type': 'TAKER',
                            'running_trading_volume': 'XXX'},
                    'trade': {'account_id': 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx',
                              'amount': 'XXX',
                              'instrument_code': 'LTC_EUR',
                              'order_id': 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx',
                              'price': 'XXX',
                              'price_tick_sequence': 0,
                              'sequence': 1663679815,
                              'side': 'BUY',
                              'time': '2021-04-22T00:00:00.000000Z',
                              'trade_id': 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx'}},
                   {'fee': {'collection_type': 'BEST',
                            'fee_amount': 'XXX',
                            'fee_currency': 'BEST',
                            'fee_group_id': 'default',
                            'fee_percentage': '0.12',
                            'fee_type': 'TAKER',
                            'running_trading_volume': 'XXX'},
                    'trade': {'account_id': 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx',
                              'amount': 'XXX',
                              'instrument_code': 'BEST_EUR',
                              'order_id': 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx',
                              'price': 'XXX',
                              'price_tick_sequence': 0,
                              'sequence': 1663674738,
                              'side': 'BUY',
                              'time': '2021-04-22T00:00:00.000000Z',
                              'trade_id': 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx'}},
                   {'fee': {'collection_type': 'STANDARD',
                            'fallback_reason': {'best_balance': {'available': 'XXX',
                                                                 'locked': 'XXX',
                                                                 'needed': 'XXX'},
                                                'caused_by': 'INSUFFICIENT_FUNDS'},
                            'fee_amount': 'XXX',
                            'fee_currency': 'EUR',
                            'fee_group_id': 'default',
                            'fee_percentage': '0.15',
                            'fee_type': 'TAKER',
                            'running_trading_volume': 'XXX'},
                    'trade': {'account_id': 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx',
                              'amount': 'XXX',
                              'instrument_code': 'ETH_EUR',
                              'order_id': 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx',
                              'price': 'XXX',
                              'price_tick_sequence': 0,
                              'sequence': 1663646554,
                              'side': 'SELL',
                              'time': '2021-04-22T00:00:00.000000Z',
                              'trade_id': 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx'}}]}
```

I don't know how fees are handled in regards to taxation, though.

In regards to historical price data, the relevant API endpoints seem to be either https://developers.bitpanda.com/exchange/#price-ticks-for-instrument or https://developers.bitpanda.com/exchange/#candlesticks (?)

**Comment by provinzio** [comment]
Hey @uvok,

I appreciate your contribution and am looking forward to your PR. Feel free to ask questions.

In Germany, Fees are accounted as losses and therefore reduce the amount to be taxed: `Sell profit - Buy cost - Fees = taxed amount`). I'd believe that each country handles it like this.

To implement another exchange, it's enough to add functions for reading in statements (`book.py`) and getting price data (`price_data.py`). The taxation is handled separatly. You might want to have a look at the different operations in `operations.py` to know, what you have to read from your statements (actually everything :D).

**Comment by uvok** [comment]
I just noticed, the existing exchanges are implemented via CSV import. I guess this is currently preferred over fetching the data via HTTPS/JSON (At least for the transactions / trades)?

**Comment by provinzio** [comment]
I prefer it, because it forces you to get an "official" hard copy of your statements which you could hand over. 

Just fetching the transactions might be more comfortable but it leaves you with only your implementation and transaction cache, when the tax bureau asks for raw data.

**Comment by uvok** [comment]
I didn't consider that, but indeed, the "paper trail" is important.

In regards to the PR.  In book.py, function detect_exchange, currently only the first row in considred. For Bitpanda Pro, there's both "transactions" (withdrawals and deposits) and "trades". The first row is the same, though:

For trades:

```
"Disclaimer: All data is without guarantee, errors and changes are reserved."
"Account ID: df2cba2e-1d43-40d9-bd73-40dc761c7d2b"
"Bitpanda Pro trade history"
Order ID,Trade ID,Type,Market,Amount,Amount Currency,Price,Price Currency,Fee,Fee Currency,Time (UTC)
```


For transactions:

```
"Disclaimer: All data is without guarantee, errors and changes are reserved."
"Account id : df2cba2e-1d43-40d9-bd73-40dc761c7d2b"

"Bitpanda Pro transactions history"
"Transaction ID","External Transaction ID",Type,In/Out,Internal/External,Amount,Currency,Fee,"Time Created"
```

So I need to read more than one row to be sure what type of file. How would you suggest handling this?

**Comment by scientes** [comment]
The transaction history is not really relevant( at least in germany) the trades are the only thing currently used to dertermine taxes. as a short term solution.
but you could use "Disclaimer: All data is without guarantee, errors and changes are reserved." as the header detection and then differentiate in the file read function. 
Option2 would be to change the header detection function to allow multiline detection

**Comment by provinzio** [comment]
Stupid question, but is it important to have two different functions to read-in the statements? You could handle both files equally. I think option 1 from scientes could be enough.

**Comment by uvok** [comment]
@scientes I would say the transaction statement might important, since it also contains Crypto Deposits.  Without them, I may get a "unmatched buy/sell positions" error. (Which actually happened to me).

Although, to be fair, you can't reliably calculate taxes if you don't know when the (deposited) coins were originally bought, and you just have the deposit date. That's actually pretty tricky. I guess I'll just edit out the affected trades for me, (Sold deposited coins).

**Comment by scientes** [comment]
currently all deposit and withdraw statements are ignored due to the unclear buy and sell date of withdrawals and deposits

**Comment by provinzio** [comment]
The only thing deposit days are good for, is to check the 1 year holding time (currently not implemented). 

When it's less than 1 year, you definitely need the buy operation, because you need to know thee price for which you bought the coins.

**Comment by uvok** [comment]
Do you expect the entered Buy and Sell actions to be including or excluding fees?

I.e. the statement says I bought 1 COIN for 1 EUR and paid 0.01 COIN fee, so in the end, I only got 0.99 COIN. Do I need to enter 1 COIN or 0.99 COIN in `append_operation`?

**Comment by scientes** [comment]
look at the coinbase implementation, coinbase also includes fees in their trade rows

**Comment by uvok** [comment]
I don't know whether Coinbase already removes their fee from the purchases (or sales) in their statement, though. I also based my implementation in Coinbase, though I decided not to do buy and sell EUR, but the coins themselves.

Not sure if this related, with my current implementation, I get a warning in the logger:

```
 WARNING  Balance has outstanding fees which were not considered: 5.39931863 EUR
```

**Comment by scientes** [comment]
I Do Not know this either if coinbase substracts These. Binance for instance does Not. And Has them as a separate transaction in their report.

**Comment by uvok** [comment]
I finished implementing the REST API for the BEST fees now. I still get the warning about outstanding fees, though.

**Comment by scientes** [comment]
I think they need to be a New issue because coinbase has the Same Problem

**Comment by provinzio** [comment]
Mhhh, the fees in EUR might be buggy. As far as I remember, the fees are removed from the Balance queue. The "lost coins" are therefore not considered anymore. 

EUR fees should be saved separatly and removed from the taxes amount at the end of the taxation period.

**Comment by dueringa** [comment]
When fetching price data, does it make sense to log a warning if the price spread is over a certain threshold? Say, 3% (I have no idea whether this is a "good" value).

Due to the current implementation of using "candlesticks" and just using the average, this might lead to "incorrect" results. (Maybe I'll also create a new PR which actually looks at either the closest trade, or the latest, like the Kraken implementation does).

**Comment by uvok** [comment]
When fetching price data, does it make sense to log a warning if the price spread is over a certain threshold? Say, 3% (I have no idea whether this is a "good" value).

Due to the current implementation of using "candlesticks" and just using the average, this might lead to "incorrect" results. (Maybe I'll also create a new PR which actually looks at either the closest trade, or the latest, like the Kraken implementation does).

**Comment by provinzio** [comment]
It might be best if all price gather functions use the same style. So I back your idea.

My current personal opinion on this topic is to get the next trade after the timestamp. Because in tax law, each trade is virtually converted to the country fiat. A realistic way to do this, is to get the "fastest" trade(s) to the fiat currency.

**Comment by uvok** [comment]
What also completely boggles my mind is this whole "BEST token" thing on Bitpanda. On one hand, it's a "normal" crypto currency, on the other hand, it can be used to pay the trading fees. (It's always the current price at the time of the trade that counts for the fee calculation, not the price at the time of buying, which would make this problem nonexistent)

So technically, you can benefit from price increases of this coin, since you're paying less of them, but you can also lose if the price goes down. Does this need to be considered in the tax calculation as well?

**Comment by scientes** [comment]
Do you have buy records of Best (e. G. Your Balance is not negative)? Because binance does the Same with bnb and there that is a non issue

**Comment by uvok** [comment]
@scientes Yes, you have to buy this token to pay fees with it

**Comment by scientes** [comment]
Then it will be considered by the tax calculation.
