### ISSUE TITLE
Are fees in EUR recognized?

### ISSUE THREAD

**Issue by provinzio** [provinzio/CoinTaxman#45]
Fees in EUR might be buggy. As far as I remember, the fees are removed from the Balance queue. The "lost coins" are therefore not considered anymore, but EUR transactions aren't recognized as "taxable events", therefore fees in EUR might be ignored in the evaluation.

EUR fees should be saved separatly and removed from the taxes amount at the end of the taxation period. 
This might deserve an issue. 

Unfortunately I can not look into the code right now to confirm it.

_Originally posted by @provinzio in https://github.com/provinzio/CoinTaxman/issues/42#issuecomment-830839390_

**Comment by scientes** [comment]
This probably happens to all starting fiat currencies (FIAT_CLASS currencies)

**Comment by uvok** [comment]
Is this about the logger warning "Balance has outstanding fees which were not considered"?

I tested this with a very simple Bitpanda Pro statement:

```
"Disclaimer: All data is without guarantee, errors and changes are reserved."
Account ID: x
Bitpanda Pro trade history
Order ID,Trade ID,Type,Market,Amount,Amount Currency,Price,Price Currency,Fee,Fee Currency,Time (UTC)
x,x,BUY,TEST_EUR,1000,TEST,1.00,EUR,10,TEST,2021-05-01T21:27:09.292828Z
x,x,SELL,TEST_EUR,990,TEST,2.00,EUR,19.80,EUR,2021-05-03T08:27:21.891983Z
```

I  got the following console output:

```
2021-05-03 21:40:42,672 taxman       WARNING  Balance has outstanding fees which were not considered: 19.80 EUR
2021-05-03 21:40:42,675 taxman       INFO     Saved evaluation in /home/andreas/python-environments/bitpanda/CoinTaxman/export/2021_rev006.csv.

Your tax evaluation for 2021:
Sonstige Einkünfte: 960.20 EUR
```

And the following report in export:

```
# software,CoinTaxman <https://github.com/provinzio/CoinTaxman>
# commit,cea9e2adb3e3e0293176f8e5efa9849557b58b7e
# updated,05/03/21
Date,Taxation Type,Taxed Gain in EUR,Action,Amount,Asset,Remark
2021-05-01 21:27:09.292828+00:00,Sonstige Einkünfte,-10.0,Fee,10,TEST,
2021-05-03 08:27:21.891983+00:00,Sonstige Einkünfte,990.0,Sell,990,TEST,990 from 2021-05-01 21:27:09.292828+00:00 (Buy)
2021-05-03 08:27:21.891983+00:00,Sonstige Einkünfte,-19.80,Fee,19.80,EUR,
```

So although there's a warning, the fee appears in the report.

**Comment by provinzio** [comment]
The issue was already fixed in the past.
