### ISSUE TITLE
Change method for getting price for Bitpanda Pro

### ISSUE THREAD

**Issue by uvok** [provinzio/CoinTaxman#46]
As discussed in #42 :

Use the closest trade, rather than the "candlesticks" approach.

If there is a function call (`_get_price_bitpanda_pro`) to get the price at 2021-04-12T12:00:00Z:

- If there's a trade (price) at 2021-04-12T11:59:30Z, and another one at 2021-04-12T12:00:15Z, use the price of the latter one
- If there's a trade (price) at 2021-04-12T11:59:45Z, and another one at 2021-04-12T12:00:30Z, use the price of the former one

**Comment by provinzio** [comment]
It makes more sense to take the next trade (including same time). Taking a price from the past doesn't make sense, in my opinion.

**Comment by uvok** [comment]
I'm curious why that is. When there's little trading volume, there might be periods of half an hour, or even an hour, with no trades, probably also with a high price difference (though that can go both ways.). In this case, I'd find it more intuitive to use a price from 5 minutes ago than one from 30 minutes later.

I could add a parameter to the function with a default value, though, and evaluate the difference- (Though I guess for my trades that would make only a difference of few cents or fractions of it)

**Comment by provinzio** [comment]
Therefore it might be the best way to take the price before and after and do some kind of weighted average depending on the time difference.

**Comment by uvok** [comment]
It appears to me I can't get "ticks" for old trades?

The API doc says

> Returns price ticks for a specific market with an interval of maximum of 4 hours.

But there seems to be an additional limitation, if I try to get the "ticks" from >= 24 hours ago, I get an error 400 with error "INVALID_TIME_RANGE".

The "Order Book" doesn't provide from/to parameters, so it's seemingly only for the current offers/asks.

Otherwise, there seems to be no public API endpoint for getting actual trade prices, only the "candlesticks"

**Comment by provinzio** [comment]
That's unfortunate. In that case, we might have to stick to the candlesticks and can not solve this issue for bitpanda pro.
