### ISSUE TITLE
[Binance] Calculate price from transaction statement

### ISSUE THREAD

**Issue by scientes** [provinzio/CoinTaxman#50]
Currently the price for a certain transaction statement is currently not known for binance and some other exchanges.
but for binance transactions that belong together always have the correct timestamp if i'm not mistaken.
```
2021-05-09 03:25:21,Spot,Transaction Related,USDT,-21.87041400,""
2021-05-09 03:25:21,Spot,Fee,BNB,-0.00002523,""
2021-05-09 03:25:21,Spot,Buy,VET,98.10000000,""
```
Thus the absolute of Transaction Related divided by buy should give us the price of VET/USDT without requiring an api request.
98.1/21.8741400=0.2294

This does not work for all statements but should improve the accuracy of some and the speed (if we have eur as base fiat we'd need to compute the USDT/EUR but we would save probably 1 api request)

**Comment by provinzio** [comment]
done with the above PR.
