### ISSUE TITLE
Regonize speculation period (Spekulationsfrist) for lending and staking.

### ISSUE THREAD

**Issue by provinzio** [provinzio/CoinTaxman#57]
According to a draft of the Federal Ministry of Finance of Germany ("Bundesfinanzministerium"), coin lending and staking raises the speculation period ("Spekulationsfrist") from one to ten years.

We shoud adjust the way, staking and lending profits are handled by CoinTaxman.

For me, it stays unclear whether FIFO has to be followed or not.
Example:
1. I buy a coin
2. I buy a second coin
3. I stake one coin: Which coin do I stake? Do I have to use FIFO? Let's assume I stake the first coin.
4. I wait so that both coins are older than 1 year. I am still staking the first coin.
4. I sell a coin: Which coin do I sell? According to FIFO I have to sell the first coin which is currently staked and pay taxes on it because of the increased speculation period. But I'd rather sell the seconds coin, which is actually the only one available for me.

German Source:
https://www.heise.de/news/Fuer-Proof-of-Stake-genutztes-Kryptogeld-erst-nach-10-Jahren-steuerfrei-6114198.html
Draft of BMF: https://www.bundesfinanzministerium.de/Content/DE/Downloads/BMF_Schreiben/Steuerarten/Einkommensteuer/2021-06-17-est-kryptowaehrungen.pdf?__blob=publicationFile&v=2

**Comment by scientes** [comment]
NExt question is what happens with defi stuff like swaps, does that apply there too?

**Comment by Griffsano** [comment]
Correct me if I'm wrong (I'm still wrapping my head around the code), but currently staking/unstaking does not have any impact on the calculation, right?
Although I have no solid argument for it, I would go for FIFO staking, as this makes more sense to me. Similar to the discussions in https://github.com/provinzio/CoinTaxman/issues/86 regarding separate wallets and https://github.com/provinzio/CoinTaxman/issues/4 for deposits/withdrawals, I would assume that I cannot sell a coin that I staked. Therefore, in your example, I would also sell the second coin first.

**Comment by Griffsano** [comment]
What do you think of moving staked coins to a virtual "wallet/exchange" in order to "block" them? For example, when a coin on Kraken is staked, it is transferred from exchange "kraken" to virtual exchange "kraken-staked", and when it is unstaked, it is transferred from "kraken-staked" back to "kraken".
This way, we can re-use the FIFO/LIFO logic from deposit and withdrawals (#4, needs to be implemented first), and staked coins are moved "out of the way" for FIFO/LIFO trading. By just adding "-staked" or something similar to the exchange, we also always know the correct exchange of the staked coins.

**Comment by provinzio** [comment]
I thought of this idea a lot and I think this is the only way, to accomplish a good FIFO logic on coins. It just doesn't make sense to sell staked coins... Using the suffix `-staked` on the platform is a great idea, reusing #4 👍

**Comment by tobias-p** [comment]
I read a news about the speculation period is set back to 1 year. (news in german language) [Anwalt.de v 29.04.22](https://www.anwalt.de/rechtstipps/neuer-sachstand-bmf-schreiben-zu-kryptowaehrungen-und-10-jahres-frist-finanzamt-bitcoin-nft-token-200209.html)

**Comment by provinzio** [comment]
Definitely good news for us! Thank you @tobias-p.

Therefore, this issue can be closed.

**Comment by provinzio** [comment]
Official so

> I read a news about the speculation period is set back to 1 year. (news in german language) [Anwalt.de v 29.04.22](https://www.anwalt.de/rechtstipps/neuer-sachstand-bmf-schreiben-zu-kryptowaehrungen-und-10-jahres-frist-finanzamt-bitcoin-nft-token-200209.html)

Official source from BMF.

https://www.bundesfinanzministerium.de/Content/DE/Pressemitteilungen/Finanzpolitik/2022/05/2022-05-11-ertragsbesteuerung-von-virtuellen-waehrungen.html

The final BMF document got released.

https://www.bundesfinanzministerium.de/Content/DE/Downloads/BMF_Schreiben/Steuerarten/Einkommensteuer/2022-05-09-einzelfragen-zur-ertragsteuerrechtlichen-behandlung-von-virtuellen-waehrungen-und-von-sonstigen-token.html
