### ISSUE TITLE
Unable to detect the exchange of file

### ISSUE THREAD

**Issue by tkso1997** [provinzio/CoinTaxman#77]
I get an "Unable to detect the exchange of file" when trying to start the program?

My account_statement is from binance. Is there anything else apart from moving the CSV file to the account_statements folder that I need to do before starting?

**Comment by provinzio** [comment]
Have you downloaded the correct transaction file? Check the wiki for more informations. 

You shouldn't have to do anything else.

**Comment by tkso1997** [comment]
okidoki, ill check again.

**Comment by tkso1997** [comment]
Did not work ...

the file looks like the following:


User_ID,UTC_Time,Account,Operation,Coin,Change,Remark |  
-- | --
26323898,2021-06-19 07:48:37,Spot,Distribution,NFT,753662.16095100,""
26323898,2021-07-19 10:56:47,Spot,Sell,CTSI,-34.70000000,"" |  
26323898,2021-07-19 10:56:47,Spot,Sell,CTSI,-33.00000000,"" |  
26323898,2021-07-19 10:56:47,Spot,Fee,BNB,-0.00003267,"" |  

plus many rows more.

is this the right format?
An do I have to check any special things while generating the file. For instance hide transfer record?

**Comment by tkso1997** [comment]
Do you have a dummy file that I could test?

**Comment by scientes** [comment]
It should Look like this:

https://github.com/provinzio/CoinTaxman/blob/f6270d696a27a9074961825cf2e02a5e61e9f741/test/binance.csv

**Comment by scientes** [comment]
But it looks like binance changes their Export Format a little due to having user_id infront

**Comment by tkso1997** [comment]
My file definitely looks different

**Comment by scientes** [comment]
yes you have an extra row in the front, but the rest sees the same

**Comment by tkso1997** [comment]
Okay I’ll try to remove that manually

**Comment by lkpythontest** [comment]
I had the same error and i fixed it, its acutally not much of an issue. I am new to github and dont know how to show it to you

**Comment by lkpythontest** [comment]
ill try it this way: at the detect_exchange() you have to add "User_ID" at binance. Also at the _read_binance() in the for loop you have to add another variable as it iterates through the rows, eg. "user_id".

**Comment by provinzio** [comment]
> I had the same error and i fixed it, its acutally not much of an issue. I am new to github and dont know how to show it to you

No problem. In case you are interested, this guy has a good and short tutorial on how to fork a GitHub Repository and submit a Pull Request https://jarv.is/notes/how-to-pull-request-fork-github/.

**Comment by provinzio** [comment]
Fixed with #88
