### ISSUE TITLE
[Question] Previous commit (sort_operations) changed result

### ISSUE THREAD

**Issue by uvok** [provinzio/CoinTaxman#81]
Hello.

I noticed that a previous commit, namely 41d4bd6e1af23dd07cf117256e18217e4597bca6, changed the result I get for the program run.

I already sorted the CSV files from Bitpanda by UTC timestamp (since they are in completely random order), but that didn't change the result.

Previously, the result was

```
Your tax evaluation for 2021:
Sonstige Einkünfte: 100.6064681074969500000000000 EUR
```

After the commit, the result is

```
Your tax evaluation for 2021:
Sonstige Einkünfte: 84.37055697785535000000000000 EUR
```

I can see a difference in the exported CSVs (Remark column) in regards to which coins are used. However, I'm not quite sure why that is. E.g. the sums of coins "used" for a given date are not the same, which strikes me strange.

**Comment by scientes** [comment]
> I already sorted the CSV files from Bitpanda by UTC timestamp (since they are in completely random order), but that didn't change the result.

The entries are bring sorted by timestamp so sorting beforehand should not make a difference

> Also, a sell operation from 2021-04-05 has in its remark column that is uses coins from a buy operation from 2021-04-22, which clearly cannot be.

That surely is Strange

**Comment by uvok** [comment]
I went through the account statements manually (for an LTC operation where the bug occurred). Unless I did something wrong with the tax calculation in my Bitpanda Exchange, there should be enough coins, no need to take coins from 2021-04-22 on 2021-04-05.

**Comment by uvok** [comment]
I'm doing a bit of debugging. In taxman.py, line 198, after the sort_operations call, the operations seem to be bunched up in order All Buy - All Fee - All sell.

Is this processed in this order regardless of the date? Shouldn't Fees and Sells be processed "together" by date?

**Comment by uvok** [comment]
I'm not so familiar with Python and sorting.

Does transaction.py:186 needs to be changed to

```py
return tuple([getattr(op, key) for key in keys] if keys else [] + [idx])
```

?

**Comment by provinzio** [comment]
`return tuple(([getattr(op, key) for key in keys] if keys else []) + [idx])` maybe with brackets like this? I am currently not at my workstation and can not test it right now.
