### ISSUE TITLE
Binance: CSV Field Change

### ISSUE THREAD

**Issue by Griffsano** [provinzio/CoinTaxman#85]
It seems the data fields of the Binance CSV export have changed. This is the first line of my current export:
`User_ID,UTC_Time,Account,Operation,Coin,Change,Remark`

The `User_ID` is new. I'll make the necessary adaptions in the code to support the new file format.

Edit: This seems to be a duplicate of #77 and can be resolved by #78. Alternatively, I can also create a pull request for my modifications.

**Comment by provinzio** [comment]
Feel free to finish the work of #78 with you own PR

**Comment by provinzio** [comment]
Fixed with #88
