### ISSUE TITLE
FIFO calculation per exchange, or total?

### ISSUE THREAD

**Issue by uvok** [provinzio/CoinTaxman#86]
Hi,

according to https://cryptotax.io/fifo-oder-lifo-bitcoin-gewinnermittlung/, the FIFO queue is supposed to be calculated per exchange.
Quickly glancing over the code, I think currently CoinTaxman collects all operations in a single queue and then does the FIFO calculation.
So if I put statements of multiple exchanges in the account_statements directory, the calculation might be incorrect.

Current workaround is to rename "unused" account statements to .csvx, .bak, or whatever, so they are not collected.

**Comment by provinzio** [comment]
If we change this, we have to acknowledge withdrawals and deposits between two exchanges. This is currently not supported. Does the withdrawal of coins also use FIFO principal?

**Comment by uvok** [comment]
Personally, I do not know that.

**Comment by provinzio** [comment]
In essence, however, I agree with your objection. The transactions should be evaluated separately according to depots. I've adapted the code accordingly. Currently only a warning is issued if there are disregarded deposits or withdrawals.

**Comment by uvok** [comment]
Cross-Linking issue from Rotki: https://github.com/rotki/rotki/issues/2438

Can this be made configurable?

**Comment by provinzio** [comment]
> Cross-Linking issue from Rotki: [rotki/rotki#2438](https://github.com/rotki/rotki/issues/2438)
> 
> Can this be made configurable?

Should be really easy. Add a variable to config and extend taxman.evaluate_taxation with an if case.

**Comment by provinzio** [comment]
@uvok there you go
