### ISSUE TITLE
Feature: Detailed export with all actions

### ISSUE THREAD

**Issue by Griffsano** [provinzio/CoinTaxman#94]
It would be nice to have a detailed table/CSV that lists all actions including buys, prices used for calculation and total values.
This would also enhance transparency of how the gains/losses are calculated and on what price basis.

Additional actions that could be listed are staking/unstaking. This issue could be tackled together with https://github.com/provinzio/CoinTaxman/issues/95 and https://github.com/provinzio/CoinTaxman/issues/53.

**Comment by scientes** [comment]
This would be a nice addition, but could be a lot of work depending in how detailed we want to do this

**Comment by provinzio** [comment]
All tax events are exported as csv.

https://github.com/provinzio/CoinTaxman/blob/main/src/taxman.py#L309-L361

If you want a more detailed export, we could add another list e.g. `self.all_events` or adjust the `TaxEvent` class with a boolean `is_taxable` and add all actions we want to see in the final evaluation.

**Comment by provinzio** [comment]
I am currently reworking the taxation and export. This feature should come with it.
