### ISSUE TITLE
Feature: List unsold coins

### ISSUE THREAD

**Issue by Griffsano** [provinzio/CoinTaxman#95]
It would be nice to have a detailed table/CSV that lists all unsold coins with their buy date and price.
This would make it easier to track which coins will get tax-free soon and, if they would be sold earlier, if that would result in a gain or loss.

This issue could be tackled together with https://github.com/provinzio/CoinTaxman/issues/94 and https://github.com/provinzio/CoinTaxman/issues/53.

**Comment by scientes** [comment]
yep i thought about that yesterday^^ would be nice

**Comment by provinzio** [comment]
I implemented a console output to list the unsold coins. Check out the `virtual sell` config option. It should be easy to add the buy dates for each coin and even transform it to an csv output.

https://github.com/provinzio/CoinTaxman/blob/main/src/config.py#L33-L35

https://github.com/provinzio/CoinTaxman/blob/main/src/taxman.py#L283-L307

**Comment by provinzio** [comment]
I am currently reworking the taxation and export. This request should come with it.
